version: "3"
services:
  fastapi:
    image: "originaldcam:python"
    ports:
      - 8000:8000
    volumes:
      - "/home/denzel/projects/LifeScript/backend/src:/backend/src"
      - "/home/denzel/projects/LifeScript/backend/requirements.txt:/src/requirements.txt"
    environment:
      - WATCHFILES_FORCE_POLLING=true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
