version: "3"
services:
  fastapi:
    image: "backend:fastapi"
    ports:
      - 80:8000
    volumes:
      - "${PWD}/src:/backend/src"
      - "${PWD}/alembic.ini:/backend/alembic.ini"
      - "${PWD}/requirements.txt:/backend/requirements.txt"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_LISTEN_ADDRESS: "${PGADMIN_LISTEN_ADDRESS}"
      PGADMIN_LISTEN_PORT: "${PGADMIN_LISTEN_PORT}"
    ports:
      - 8080:8080
