version: "3"
services:
  backend:
    image: "lifescript:backend"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    volumes:
      - "${PWD}/src:/backend/src"
      - "${PWD}/alembic.ini:/backend/alembic.ini"
      - "${PWD}/requirements.txt:/backend/requirements.txt"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_TEST_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - ${POSTGRES_TEST_PORT}:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_LISTEN_ADDRESS: "${PGADMIN_LISTEN_ADDRESS}"
      PGADMIN_LISTEN_PORT: "${PGADMIN_LISTEN_PORT}"
    ports:
      - 8080:8080
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin:
