version: "3"
services:
  fastapi:
    image: "originaldcam:python"
    ports:
      - 8000:8000
    volumes:
      - "/home/denzel/projects/LifeScript/backend/src:/backend/src"
      - "/home/denzel/projects/LifeScript/backend/alembic.ini:/backend/alembic.ini"
      - "/home/denzel/projects/LifeScript/backend/requirements.txt:/backend/requirements.txt"
    environment:
      - WATCHFILES_FORCE_POLLING=true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_LISTEN_ADDRESS: "${PGADMIN_LISTEN_ADDRESS}"
      PGADMIN_LISTEN_PORT: "${PGADMIN_LISTEN_PORT}"
    ports:
      - 8080:8080
